# Generated by Django 5.1.5 on 2025-05-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_docuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="docuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Author"),
                    ("officer", "Officer"),
                    ("user", "user"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
